- munetic_express/.env.sample
- munetic_express/.gitignore
- munetic_express/package-lock.json
- munetic_express/package.json
- munetic_express/src/app.ts
- munetic_express/src/config/config.ts
- munetic_express/src/models/category.ts
- munetic_express/src/models/index.ts
- sequelize 설치 및 mariadb 연결
- Category 모델 생성
> feat: #27 set sequelize and create Category model

- munetic_admin/.eslintrc.js
- munetic_admin/.prettierrc
- munetic_admin/package-lock.json
- munetic_admin/package.json
- munetic_admin/src/App.tsx
- munetic_admin/src/main.tsx
- munetic_app/.eslintrc.js
- munetic_app/.prettierrc
- munetic_app/package-lock.json
- munetic_app/package.json
- munetic_app/src/App.tsx
- munetic_app/src/main.tsx
- munetic_express/.prettierrc
- app, admin 에  eslint, prettier 세팅 적용
- 적용으로 인한 App.tsx, main.tsx 파일 변경됨(double quote->single quote, 불필요한 () 삭제)
> style: #25 eslint,prettier-front

- munetic_admin/.eslintrc.js
- munetic_admin/.prettierrc
- munetic_admin/package-lock.json
- munetic_admin/package.json
- munetic_app/.eslintrc.js
- munetic_app/.prettierrc
- munetic_app/package-lock.json
- munetic_app/package.json
- munetic_app/src/pages/HomePage.tsx
- munetic_express/.eslintrc.js
- munetic_express/.prettierrc
- munetic_express/package-lock.json
- munetic_express/package.json
develop 브랜치에 airbnb 스타일 eslint, prettier 설정 적용
- app, admin, express 각각 .eslintrc.js, .prettierrc 파일 생성
- main 브랜치에 eslint, prettier 적용시킬때와 같은 상태로 package.json 변경
package.json 내 dependencies, devDependencies
작업 환경 및 코드 스타일을 통일하여 협업을 용이하게 하기 위함
> feat: common #41 eslint, prettier adapt to develop

- munetic_admin/package-lock.json
- munetic_admin/package.json
- munetic_app/package-lock.json
- munetic_app/package.json
react-router-dom 패키지가 누락된 부분 수정
admin, app 각 package.json 에 react-router-dom 추가
package.json 파일
버그 수정
> fix: close #41 router-dom package add

- munetic_admin/Dockerfile
- munetic_app/Dockerfile
- munetic_express/Dockerfile
- munetic_proxy/conf.d/app.conf
도커파일에 변경되지 않은 사항이 있어서 변경함
Dockerfile 내에서 nom i esbuild 실행
서버에서 제대로 빌드될 것으로 기대함
서버에서 빌드하기
> fix: CD/CD #51 fix Dockerfile to install esbuild

- munetic_express/src/controllers/auth.controller.ts
- munetic_express/src/models/lesson.ts
- munetic_express/src/models/user.ts
- munetic_express/src/modules/reshape.ts
- munetic_express/src/swagger.yml
- munetic_express/src/tests/dummy/userInstance.ts
feat:express #6 add gender feild in user model
- user gender field 추가
- lesson gender field 삭제
- signup api 수정
- swagger 수정
> feat:express #6 add gender field in user model

- munetic_app/src/components/auth/Login.tsx
- munetic_app/src/lib/api/auth.ts
- munetic_app/src/lib/api/client.ts
- app 회원가입 api 연결
- app 에서 axios baseURL 설정 localhost:3030 으로 변경
- auth 의 post, get 요청 url 변경(/auth/signup -> /api/auth/signup)
- 회원가입 가능
- 회원가입
> feat: app 회원가입 api 연결

- munetic_express/src/controllers/auth.controller.ts
- munetic_express/src/modules/jwt.strategy.ts
- munetic_express/src/modules/local.strategy.ts
- munetic_express/src/routes/auth.routes.ts
- munetic_express/src/service/user.service.ts
- munetic_express/src/swagger.yml
feat:express #94 access/refresh token api
- refreshToken 으로 accessToken 재발급하는 api 개발
> feat:express #94 access/refresh token api

- munetic_express/src/routes/user.routes.ts
- munetic_express/src/swagger.yml
user api 수정
변경전
변경후
api 일관성, 확장성 증가
> feat:express #107 update user api

- docker-compose.yaml
> fix: app 도커컴포즈 app env 삭제

- docker-compose.yaml
> fix: app 도커컴포즈 환경변수 재생성

- munetic_app/src/components/auth/Register.tsx
- munetic_app/src/components/common/Input.tsx
버그 수정 #88 #86 #83
- #83 회원가입 시 휴대폰 번호 형식 정규표현식을 주어 true 반환해야 valid하게 함
- #86 input에 width 100% 주니까 해결..안됐었는데...
- #88 값 change 마다 valid state 초기화
- ux 상향
> Fix: app 버그 수정 #88 #86 #83

- munetic_express/src/swagger.yml
> feat: express category api swagger add

- munetic_app/src/components/Home.tsx
- munetic_app/src/pages/HomePage.tsx
- munetic_app/src/tests/Home.test.tsx
- munetic_app/src/tests/components/common/Button.test.tsx
앱 초기화면 적용
시나리오와 와이어프레임에 맞게 UI를 적용하였습니다.
기존에 동작하지 않던 app 단 jest 테스트케이스도 수정하였고 새 초기 화면에 맞게 적용하였습니다.
- 앱 초기 화면 UI
- 앱 jest 테스트케이스
> Feat: 초기 화면 UI 시나리오에 맞게 적용

- munetic_express/src/controllers/search.controller.ts
- munetic_express/src/routes/index.ts
- munetic_express/src/routes/search.routes.ts
- munetic_express/src/service/category.service.ts
- munetic_express/src/service/search.service.ts
- munetic_express/src/service/user.service.ts
- munetic_express/src/swagger/apis/search.yml
검색 기능에 대한 search HTTP API 추가
- 검색 기능을 위한 검색 라우터, 컨트롤러, 서비스, Swagger 명세 추가
- 검색 기능을 위한 검색 라우터, 컨트롤러, 서비스, Swagger 명세 추가
검색 페이지에서 활용을 위해
> [feat] 검색 기능 HTTP API

- munetic_app/src/Routing.tsx
- munetic_app/src/components/Wrapper.tsx
- munetic_app/src/components/common/Button.tsx
- munetic_app/src/components/like/MyLikeLessons.tsx
- munetic_app/src/components/profile/ManageProfile.tsx
- munetic_app/src/components/profile/ViewTutorsProfile.tsx
- munetic_app/src/pages/profile/ViewMyLikesPage.tsx
좋아요 누른 강의를 볼 수 있는 페이지 추가
좋아요 누른 강의를 볼 수 있는 페이지 추가
메인페이지 css 변경
> feat: #180 added liked lessons page

- munetic_app/src/Routing.tsx
- munetic_app/src/components/bookmark/MyBookmarkLessons.tsx
- munetic_app/src/components/buttons/BookmarkButton.tsx
- munetic_app/src/components/buttons/LikeButton.tsx
- munetic_app/src/components/lesson/Class.tsx
- munetic_app/src/lib/api/bookmark.ts
- munetic_app/src/pages/bookmarks/ViewMyBookmarksPage.tsx
- munetic_express/src/app.ts
- munetic_express/src/controllers/bookmark.controller.ts
- munetic_express/src/models/bookmark.ts
- munetic_express/src/service/bookmark.service.ts
기존 북마크 API 개선 및 북마크 기능 추가
- 북마크 기능 추가
- 북마크 버튼 동작
- 북마크 페이지에서 북마크 한 강의들 열람 가능
- 북마크 API 및 DB 컬럼 수정
> feat: #173 북마크 기능 추가

- munetic_app/src/Routing.tsx
잘못된 merge 충돌 수정으로 인한 버그 수정
누락된 라우팅 import 추가
누락된 라우팅 import 추가
버그 수정
> fix: added routing import

- munetic_app/src/components/Search.tsx
- munetic_app/src/components/bookmark/MyBookmarkLessons.tsx
- munetic_app/src/components/lesson/ClassList.tsx
- munetic_app/src/components/lesson/ClassManage.tsx
- munetic_app/src/components/lesson/lessonlist/LessonItem.tsx
- munetic_app/src/components/like/MyLikeLessons.tsx
- munetic_app/src/components/profile/ViewProfile.tsx
#189 에 대한 작업 사항
중복으로 반복해서 사용되는 여러개의 리스트 컴포넌트를 하나의 컴포넌트로 정의해 두고
리스트 컴포넌트를 import하여 사용하도록 변경하였습니다.
리스트 컴포넌트가 받는 프로퍼티 (인터페이스) 단순화
리스트 컴포넌트 UI 개선
코드의 기능 개선
> feat: #189 modified lesson component

- munetic_app/src/components/lesson/ClassList.tsx
- munetic_app/src/components/lesson/lessonlist/LessonItem.tsx
- munetic_app/src/types/commentData.d.ts
- munetic_app/src/types/lessonData.d.ts
- munetic_app/src/types/lessonLikeData.ts
- munetic_express/src/models/index.ts
- munetic_express/src/service/lesson.service.ts
강의 목록 요소 변경
강의 목록에 들어갈 요소들 대표님이 주신 figma대로 변경
(+ 강사이름, 지역, 가격, 댓글 수/좋아요 수)
강의 목록에 들어갈 요소들
> [feat] 강의 목록 개선

- munetic_app/src/components/lesson/lessonlist/LessonItem.tsx
#210 이슈에 대한 문제 해결
- 리액트 프로퍼티의 인터페이스에 멤버로 강제되어 있는 인자들 optional로 변경
- 리액트 프로퍼티의 인터페이스에 멤버로 강제되어 있는 인자들 optional로 변경
버그 해결
> [fix] #210 fixed component bug

- README.md
- munetic_app/README.md
- munetic_database/README.md
- munetic_express/README.md
readme 문서 개선
#208 참조
#208 참조
용이한 인수인계 및 유지보수, 문서화를 위함
> [docs] #208 readme 문서 개선

- munetic_app/src/components/lesson/ClassWrite.tsx
- munetic_app/src/components/ui/DateSelect.tsx
- munetic_express/src/service/lesson.service.ts
- munetic_express/src/types/service/lesson.service.d.ts
#212 에 대한 버그들 수정
#212 에 대한 버그들
> [fix] #212 fixed bugs

- munetic_admin/src/components/Menu/menuLists.ts
- munetic_admin/src/components/Routing.tsx
- munetic_admin/src/components/Table/Comment/CommentHeadCell.tsx
- munetic_admin/src/components/Table/Comment/CommentHeadCells.ts
- munetic_admin/src/components/Table/MUITableHead.tsx
- munetic_admin/src/components/Table/MUITableRow.tsx
- munetic_admin/src/components/Table/MUITableToolbar.tsx
- munetic_admin/src/lib/api.ts
- munetic_admin/src/pages/CommentListPage.tsx
- munetic_express/src/controllers/comment.controller.ts
- munetic_express/src/routes/admin/admin.routes.ts
- munetic_express/src/routes/admin/comment.routes.ts
- munetic_express/src/service/comment.service.ts
- munetic_express/src/util/addProperty.ts
관리자 페이지에서 댓글 및 평점 조회기능 추가
#205
#205
> [feat] #205 add comments view

- munetic_app/src/components/lesson/Class.tsx
- munetic_app/src/components/lesson/ClassWrite.tsx
- munetic_app/src/lib/api/lesson.ts
- munetic_express/src/controllers/lesson.controller.ts
- munetic_express/src/routes/lesson.routes.ts
- munetic_express/src/service/lesson.service.ts
대표님께서 요청하신 수정사항)
동일한 카테고리에 한 강사가 두 개 이상 레슨글을 쓸 수 없도록 막아야 함
강사가 본인 게시물을 최신 게시물로 "끌어올리는" 기능 구현 (강의 수정 페이지에서 구현, 쿨타임은 1시간)
#204 
#204
> [feat] 강의 등록 및 수정 관련

- munetic_app/src/components/auth/TutorRegister.tsx
- munetic_app/src/components/lesson/LessonInfo.tsx
- munetic_app/src/components/profile/ViewProfile.tsx
- munetic_app/src/components/ui/SnsButtons.tsx
- munetic_app/src/lib/api/profile.ts
- munetic_app/src/pages/lesson/ClassPage.tsx
- munetic_express/src/controllers/auth.controller.ts
- munetic_express/src/controllers/user.controller.ts
- munetic_express/src/routes/user.routes.ts
- munetic_express/src/service/tutorInfo.service.ts
- munetic_express/src/service/user.service.ts
> [feat] #196 에 대한 작업 사항

- munetic_admin/src/components/Table/MUITableHead.tsx
> [fix] #218 bug fixed

- munetic_app/src/components/home/LoggedIn.tsx
- munetic_app/src/components/lesson/ClassWrite.tsx
- munetic_app/src/components/lesson/LessonInfo.tsx
- munetic_app/src/components/media/VideoEmbed.tsx
- munetic_app/src/lib/getYoutubeId.ts
- munetic_app/src/types/lessonData.d.ts
- munetic_express/src/models/lesson.ts
- munetic_express/src/seeders/20211218124842-Lesson.js
- munetic_express/src/service/lesson.service.ts
> [feat] #193 강의에 유튜브 영상 임베드 추가

- munetic_app/src/components/Home.tsx
- munetic_app/src/components/home/LoggedIn.tsx
- munetic_app/src/components/profile/ViewTutorsProfile.tsx
- munetic_app/src/lib/api/auth.ts
- munetic_app/src/lib/api/comment.ts
- munetic_app/src/lib/api/like.ts
- munetic_app/src/lib/auth/loginCheck.ts
- munetic_app/src/lib/auth/logout.ts
- munetic_app/src/types/commentData.d.ts
- munetic_app/src/types/lessonLikeData.d.ts
- munetic_express/src/controllers/auth.controller.ts
- munetic_express/src/controllers/comment.controller.ts
- munetic_express/src/controllers/lessonLike.controller.ts
- munetic_express/src/routes/auth.routes.ts
- munetic_express/src/routes/comment.routes.ts
- munetic_express/src/routes/lessonLike.routes.ts
- munetic_express/src/service/comment.service.ts
- munetic_express/src/service/lessonLike.service.ts
> feat: #202 added star tutor

- munetic_app/src/components/lesson/lessonlist/LessonItem.tsx
- munetic_app/src/components/profile/ViewProfile.tsx
> feat: #225 이슈에 대한 작업 사항

- munetic_app/src/components/common/Input.tsx
- munetic_app/src/components/lesson/ClassWrite.tsx
- munetic_app/src/components/ui/AddressSelect.tsx
#197 이슈에 대한 기능 구현
#197 이슈에 대한 기능 구현
> #197 added location component

- README.md
- docker-compose.yaml
- munetic_express/src/config/config.ts
- munetic_express/src/modules/reshape.ts
- munetic_express/src/service/lesson.service.ts
#168 에러를 수정하기 위한 중간 PR
- docker-compose에서 로컬 네트워크로 export하는 포트 모두 제거하고 네트워크 설정에서만 export하도록 변경
- tsc 컴파일 에러 수정
> [fix] #168 에러를 수정하기 위한 중간 PR

- .github/workflows/deployment.yml
#168 에러를 수정하기 위한 중간 PR (2)
- github action에서 호스트를 localhost로 설정하도록 변경
> #168 에러를 수정하기 위한 중간 PR (2)

- .github/workflows/deployment.yml
Reverts innovationacademy-kr/slabs-munetic#231
> Revert "#168 에러를 수정하기 위한 중간 PR (2)"

- munetic_app/src/components/lesson/LessonInfo.tsx
- munetic_app/src/components/profile/ViewProfile.tsx
- munetic_app/src/components/profile/ViewTutorProfile.tsx
코드 리뷰 피드백
콘솔로그 제거, 안사용하는 자료 제거, 경력 빈스트링 컴포넌트 생성 방지
> [fix]#237 code review feedback
